services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ml_app_network
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    command: > 
      sh -c "alembic upgrade head &&
             uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000"
    shm_size: 6gb # increase in case of error loading data when training model on docker
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: "lukstasiak/fast-api-ml-multilabel-classification"
    networks:
      - ml_app_network

  celery:
    container_name: celery
    build: .
    command: celery -A src.app.tasks worker -l INFO
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - ml_app_network

  redis:
    container_name: redis
    image: redis
    networks:
      - ml_app_network

networks:
  ml_app_network:

volumes:
  postgres_data: