services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - ml_app_network
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    image: "lukstasiak/fast-api-ml-multilabel-classification"
    networks:
      - ml_app_network

  celery:
    container_name: celery
    build: .
    command: celery -A src.app.tasks worker -l INFO
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
    image: "lukstasiak/fast-api-ml-multilabel-classification"
    networks:
      - ml_app_network

  redis:
    container_name: redis
    image: redis
    networks:
      - ml_app_network

networks:
  ml_app_network:

volumes:
  postgres_data:
