name: Python CI

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose

      - name: Build and run docker-compose
        run: |
          docker-compose -f docker-compose-gh-actions.yaml build
          docker-compose -f docker-compose-gh-actions.yaml up -d
      - name: Apply alembic migrations
        run: |
          docker-compose -f docker-compose-gh-actions.yaml exec -T web alembic upgrade head
      - name: Code check Black and Isort
        run: |
          docker-compose -f docker-compose-gh-actions.yaml exec -T web black src
          docker-compose -f docker-compose-gh-actions.yaml exec -T web isort --profile black src
      - name: Test with pytest
        run: |
          docker-compose -f docker-compose-gh-actions.yaml exec -T web pytest -v
